### ISSUE TITLE
Gap under footer in About us section [Desktop/ipad]

### ISSUE THREAD

**Issue by Hero1230** [GhostyORG/Ghosty-web#66]
There is a big gap under the footer in the about us section. It doesn't look good.
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/42366462/203796303-1cba0a1d-dc94-4aa4-947f-35632e6e1917.png">

**Comment by killerclaws12** [comment]
Yeah! We noticed. But none of us are currently able to fix this due to the holidays and schooling!

**Comment by killerclaws12** [comment]
I believe @Abir-Tx was working on this before school started. Not to sure.

**Comment by Abir-Tx** [comment]
> I believe @Abir-Tx was working on this before school started. Not to sure.

Yeah. But the gap will be omitted when we will add more info to the about us page as we had a plan to enhance the website with more useful info. So I think this will be fixed automatically when we will add more info to this page. 

Anyway I am leaving this issue as open so that if new information are not added, I can fix it

**Comment by killerclaws12** [comment]
Okay!
